/** Feel and balance constants for a run. */
export const TUNING = {
  launchSpeed: 780,
  captureTolerance: 12,
  feverCaptureTolerance: 30,
  perfectRatio: 0.55,
  maxFlightTime: 1.8,
  offscreenMargin: 30,
  planetsAhead: 4,
  cameraAnchor: 0.65,
  cameraFollow: 4,
  trailLength: 18,
  trailSpacing: 10,
  coinRadius: 26,
  powerRadius: 32,
  magnetRange: 190,
  magnetPull: 650,
  goldCoins: 5,
  milestoneEvery: 25,
  maxParticles: 240,
  bossBonus: 10,
  bossCoins: 15,
  slowmoTime: 1.2,
  slowmoScale: 0.35,
  cometSpeed: 220,
  cometRadius: 38,
  cometCoins: 10,
  cometSlowmo: 0.8,
} as const;
